Fix declaration of qsort_mt and cmp_t
Fix build with GCC-15, which is more strict about this kind of things:

```
rling.c: In function ‘main’:
rling.c:2764:28: error: too many arguments to function ‘qsort_mt’; expected 0, have 6
 2764 |             if (!IsSorted) qsort_mt(Sortlist,Line,sizeof(char **),comp1,Maxt,forkelem);
      |                            ^~~~~~~~ ~~~~~~~~
rling.c:352:13: note: declared here
  352 | extern void qsort_mt();
      |             ^~~~~~~~
```