Add -fgnu89-inline for GCC targets, fix clean target
GCC in C99 mode does not emit out-of-line copies of inline functions,
causing undefined reference to findeol on Linux. Add -fgnu89-inline
on non-Darwin platforms. Also remove stale libdb-dev comment and
simplify clean to rm all .o files.